export PATH="$HOME/bin:$PATH"
alias ls='exa -la -t modified --octal-permissions --no-permissions'
eval "$(starship init bash)"

function ssh_tunnel () {
        printf "%b" "\e[1;34mSSH tunneling through ${1} to ${2}::\e[0m\n"
        ssh -o ProxyCommand="ssh -W %h:%p root@${1}" "root@${2}"
}

function iprem () {
        printf "%b" "\e[1;34mRemoving IP ${@} from known hosts file::\e[0m\n"
        ssh-keygen -R "$@" -f ~/.ssh/known_hosts
}