---
- name: 'Deploy microk8s'
  hosts: control_plane, workers
  roles:
    - role: racqspace.microk8s
      vars:
        microk8s_plugins:
          istio: true
          ingress: true
          dns: true
        microk8s_enable_ha: true
        microk8s_group_ha: "control_plane"