---
- name: 'Install Monitoring Agent on control_plane nodes'
  hosts: microk8s_HA
  vars_files:
    deployment_vars.yml
  tasks:
    - name: Add sysdig agent 
      shell: curl -sL "https://ibm.biz/install-sysdig-agent" | bash -s -- -a "{{ monitoring_key }}" -c private.ingest.{{ region }}.monitoring.cloud.ibm.com --collector_port 6443 --secure true --tags "microk8s:control_plane"
- name: 'Install Monitoring Agent on worker nodes'
  hosts: microk8s_WORKERS
  vars_files:
    deployment_vars.yml
  tasks:
    - name: Add sysdig agent 
      shell: curl -sL "https://ibm.biz/install-sysdig-agent" | bash -s -- -a "{{ monitoring_key }}" -c private.ingest.{{ region }}.monitoring.cloud.ibm.com --collector_port 6443 --secure true --tags "microk8s:worker_node"