---
- name: 'Update all deployed systems'
  hosts: all
  tasks:
    - name: Update yum packages 
      yum: name=* state=latest
      when: ansible_facts['os_family'] == "RedHat"    
    - name: Update apt packages
      apt: upgrade=yes update_cache=yes
      when: ansible_facts['os_family'] == "Debian"   